name: Kleurrijktekenen
favicon: null
layout_spectrum: 0.8147511903662235
typography_spectrum: 0.9533831316512078
title: Kleurrijk tekenen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3392ca'
    - '#8a2b27'
    - '#c1a483'
    - '#d86e2e'
    - '#0549a2'
  brandStrength: 0.875
  lightness: 0.24177293316461146
  saturation: 0.7245749435387552
  rhythmicContrast: 0.018049792619422078
purpose: []
