name: Kleurrijktekenen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29731
title: Kleurrijk tekenen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3a5a6'
    - '#3c2222'
    - '#933e50'
    - '#a16475'
    - '#4d4c51'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
