name: Kleurrijk tekenen
favicon: null
layout_spectrum: 0.99133
typography_spectrum: 0.84682
title: Kleurrijk tekenen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#baa2ba'
    - '#e62423'
    - '#734447'
    - '#368980'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
