name: Kleurrijktekenen
favicon: null
layout_spectrum: 0.8147511903662235
typography_spectrum: 0.9533831316512078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.14147590473294258
  lightness: 0.24177293316461146
  saturation: 0.7245749435387552
  rhythmicContrast: 0.018049792619422078
purpose: []
