name: Kleurrijktekenen
favicon: null
layout_spectrum: 0.8147511903662235
typography_spectrum: 0.29731
title: Kleurrijk tekenen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131117'
    - '#ced2d7'
    - '#a7a7a8'
    - '#3e3b3c'
    - '#666462'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
